//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public int id_evento { get; set; }
        public int id_persona { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public System.DateTime hora_registro { get; set; }
        public string suceso { get; set; }
        public int id_pais { get; set; }
        public int id_departamento { get; set; }
        public int id_ciudad { get; set; }
        public int id_barrio { get; set; }
        public string descripcion_evento { get; set; }
        public System.DateTime fecha_evento { get; set; }
        public System.DateTime hora_evento { get; set; }
        public string atencion_policia { get; set; }
        public string tipo_lugar { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
