//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguridadCiudadana : DbContext
    {
        public SeguridadCiudadana()
            : base("name=SeguridadCiudadana")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<barrio> barrio { get; set; }
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<persona> persona { get; set; }
        public virtual DbSet<sugerencia> sugerencia { get; set; }
    }
}
