//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sugerencia
    {
        public int id_sugerencia { get; set; }
        public int id_persona { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public System.DateTime hora_registro { get; set; }
        public string descripcion { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
